### ISSUE TITLE
Cannot add a website

### ISSUE THREAD

**Issue by zerofancy** [trlanfeng/TRNewTab#6]
添加网站失败，错误信息：

![image](https://user-images.githubusercontent.com/40628516/72517999-51ad1d80-388f-11ea-99dd-5cb1ffc104d5.png)

![image](https://user-images.githubusercontent.com/40628516/72518018-6093d000-388f-11ea-843c-df3dd7202daa.png)

浏览器：Microsoft Edge 版本 79.0.309.65 (官方内部版本) (64 位)

**Comment by trlanfeng** [comment]
已修复并提交新版本到应用市场，等待审核
